spring.application.name=tea

spring.config.import=optional:file:.env[.properties]

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
#jwt.issuer=your_application_name
# Prefix for the token in the Authorization header
#jwt.token.prefix=Bearer
# Header field for the token
#jwt.header=Authorization

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate

logging.level.github.com.rexfilius.tea=DEBUG
logging.level.org.springframework.web=ERROR

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true