spring.application.name=tea

spring.config.import=optional:file:.env[.properties]

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
#jwt.issuer=your_application_name
# Prefix for the token in the Authorization header
#jwt.token.prefix=Bearer
# Header field for the token
#jwt.header=Authorization

spring.profiles.active=dev

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate

logging.level.github.com.rexfilius.tea=DEBUG
logging.level.org.springframework.web=ERROR
